//export * from './get-diseases.js'
//export * from './get-donations.js'
export * from './get_employees.js'
//export * from './get-laboratories.js'
//export * from './get-medical-exams.js'
//export * from './get-persons.js'
//export * from './get-quality-controls.js'
//export * from './get-requests.js'
//export * from './get-storages.js'
//export * from './get-units.js'
//
